name: deploy-prod

on:
  workflow_dispatch:
  push:
    branches:
      - "master"

env:
  CI: true

jobs:
  deploy-prod:
    runs-on: ubuntu-latest
    environment:
      name: Production
      url: www.bmcandrews.com

    steps:
    - uses: actions/checkout@v1
    - name: Setup Node from .nvmrc
      uses: actions/setup-node@v6
      with:
        node-version-file: '.nvmrc'
    - run: yarn install
    - run: yarn build
    - run: yarn export
    - name: Deploy to S3
      uses: jakejarvis/s3-sync-action@master
      with:
        args: --follow-symlinks --delete
      env:
        AWS_S3_BUCKET: ${{ secrets.AWS_S3_BUCKET }}
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        AWS_REGION: 'us-east-1'
        SOURCE_DIR: 'out'
    - name: Invalidate CloudFront Cache
      uses: chetan/invalidate-cloudfront-action@master
      env:
        DISTRIBUTION: ${{ secrets.DISTRIBUTION }}
        PATHS: '/*'
        AWS_REGION: 'us-east-1'
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
